import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Kameron } from "next/font/google";

const kameron = Kameron({
  variable: "--font-kameron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full antialiased dark", kameron.className)}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
